---
services:
  app:
    image: eplback:latest
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY:-django-insecure-temporary-for-build-only}
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - EMAIL_HOST=${EMAIL_HOST}
      - SENTRY_DSN=${SENTRY_DSN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
      - postgres

  maildev:
    image: "maildev/maildev:2.2.1"
    container_name: maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"


  redis:
    image: "redis:6"
    container_name: epl_redis
    restart: always

  postgres:
    image: "postgres:17"
    container_name: epl_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: epl
      POSTGRES_USER: epl
      POSTGRES_DB: epl
    ports:
      - "5432:5432"
    volumes:
      - epl_db:/var/lib/postgresql/data

volumes:
  epl_db:
    driver: local
