services:
  db:
    image: "postgres_12_fr"
    build: ./docker
    container_name: epl_db
    restart: unless-stopped
    environment:
    - POSTGRES_PASSWORD=epl
    - POSTGRES_USER=epl
    - POSTGRES_DB=epl
    ports:
    - "5432:5432"
    volumes:
    - epl_db:/var/lib/postgresql/data

volumes:
  epl_db:
    driver: local
