---
services:
  app:
    image: eplback:latest
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY:-django-insecure-temporary-for-build-only}
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - EMAIL_HOST=${EMAIL_HOST}
      - SENTRY_DSN=${SENTRY_DSN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
      - postgres

  redis:
    image: "redis:6"
    container_name: epl_redis
    restart: always

  postgres:
    image: "postgres_12_fr"
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: epl_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
#    ports:
#      - "5432:5432"
    volumes:
      - epl_db:/var/lib/postgresql/data

volumes:
  epl_db:
    driver: local
